# Stage 1: Build the React application
FROM node:20-alpine AS build

WORKDIR /app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar dependencias
RUN npm ci

# Copiar el resto del código fuente del frontend y configuraciones
COPY index.html ./
COPY postcss.config.js ./
COPY tailwind.config.js ./
COPY vite.config.js ./
COPY public/ ./public/
COPY src/ ./src/

# Configurar variable vacía para activar rutas relativas y proxy Nginx
ENV VITE_API_URL=""

# Ejecutar el build de Vite
RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

# Eliminar el default de Nginx
RUN rm -rf /usr/share/nginx/html/*

# Copiar el build compilado desde el Stage 1
COPY --from=build /app/dist /usr/share/nginx/html

# Copiar configuración custom de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
